modLoader = "javafml"
loaderVersion = "${forge_version_range}"
issueTrackerURL = "https://github.com/qyl27/architectury-loom-template/issues"
license = "ARR"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "Freesia Backend Mod"
authors = "qyl27"
description = '''
'''
#logoFile = ""

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "${forge_minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"
